ch_6_drill_1_calculator02buggy: src/ch_6_drill_1_calculator02buggy.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_6_drill_1_calculator02buggy.cpp -o bin/ch_6_drill_1_calculator02buggy
ch_6_drill_2_calculator02buggy: src/ch_6_drill_2_calculator02buggy.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_6_drill_2_calculator02buggy.cpp -o bin/ch_6_drill_2_calculator02buggy
ch_6_drill_3_calculator02buggy: src/ch_6_drill_3_calculator02buggy.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_6_drill_3_calculator02buggy.cpp -o bin/ch_6_drill_3_calculator02buggy
ch_6_drill_4_calculator02buggy: src/ch_6_drill_4_calculator02buggy.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_6_drill_4_calculator02buggy.cpp -o bin/ch_6_drill_4_calculator02buggy
ch_6_drill_5_calculator02buggy: src/ch_6_drill_5_calculator02buggy.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_6_drill_5_calculator02buggy.cpp -o bin/ch_6_drill_5_calculator02buggy
