ch_4_drill_1: src/ch_4_drill_1.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_1.cpp -o bin/ch_4_drill_1
ch_4_drill_2: src/ch_4_drill_2.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_2.cpp -o bin/ch_4_drill_2
ch_4_drill_3: src/ch_4_drill_3.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_3.cpp -o bin/ch_4_drill_3
ch_4_drill_4: src/ch_4_drill_4.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_4.cpp -o bin/ch_4_drill_4
ch_4_drill_5: src/ch_4_drill_5.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_5.cpp -o bin/ch_4_drill_5
ch_4_drill_6: src/ch_4_drill_6.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_6.cpp -o bin/ch_4_drill_6
ch_4_drill_7: src/ch_4_drill_7.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_7.cpp -o bin/ch_4_drill_7
ch_4_drill_8: src/ch_4_drill_8.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_8.cpp -o bin/ch_4_drill_8
ch_4_drill_9: src/ch_4_drill_9.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_9.cpp -o bin/ch_4_drill_9
ch_4_drill_10: src/ch_4_drill_10.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_10.cpp -o bin/ch_4_drill_10
ch_4_drill_11: src/ch_4_drill_11.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_drill_11.cpp -o bin/ch_4_drill_11
