ch_6_ex_1_a: src/ch_6_ex_1/ch_6_ex_1_a.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_1/ch_6_ex_1_a.cpp -o bin/ch_6_ex_1_a
ch_6_ex_1_b: src/ch_6_ex_1/ch_6_ex_1_b.cpp src/ch_6_ex_1/token_stream.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_1/ch_6_ex_1_b.cpp src/ch_6_ex_1/token_stream.cpp -o bin/ch_6_ex_1_b
ch_6_ex_2: src/ch_6_ex_2/ch_6_ex_2.cpp src/ch_6_ex_2/token_stream.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_2/ch_6_ex_2.cpp src/ch_6_ex_2/token_stream.cpp -o bin/ch_6_ex_2
ch_6_ex_3: src/ch_6_ex_3/ch_6_ex_3.cpp src/ch_6_ex_3/token_stream.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_3/ch_6_ex_3.cpp src/ch_6_ex_3/token_stream.cpp -o bin/ch_6_ex_3
ch_6_ex_4: src/ch_6_ex_4.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_4.cpp -o bin/ch_6_ex_4
ch_6_ex_6: src/ch_6_ex_6/ch_6_ex_6.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_6/ch_6_ex_6.cpp -o bin/ch_6_ex_6
ch_6_ex_8: src/ch_6_ex_8.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_8.cpp -o bin/ch_6_ex_8
ch_6_ex_9: src/ch_6_ex_9.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_9.cpp -o bin/ch_6_ex_9
ch_6_ex_10: src/ch_6_ex_10.cpp
	clang++ -Wall -std=c++17 -I../../../include src/ch_6_ex_10.cpp -o bin/ch_6_ex_10
