ch_3_ex_1_a: src/ch_3_ex_1_a.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_a.cpp -o bin/ch_3_ex_1_a
ch_3_ex_1_b: src/ch_3_ex_1_b.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_b.cpp -o bin/ch_3_ex_1_b
ch_3_ex_1_c: src/ch_3_ex_1_c.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_c.cpp -o bin/ch_3_ex_1_c
ch_3_ex_1_d: src/ch_3_ex_1_d.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_d.cpp -o bin/ch_3_ex_1_d
ch_3_ex_1_e: src/ch_3_ex_1_e.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_e.cpp -o bin/ch_3_ex_1_e
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
# ch_3_ex_1: src/ch_3_ex_1.cpp
# 	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
