ch_3_ex_1_a: src/ch_3_ex_1_a.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_a.cpp -o bin/ch_3_ex_1_a
ch_3_ex_1_b: src/ch_3_ex_1_b.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_b.cpp -o bin/ch_3_ex_1_b
ch_3_ex_1_c: src/ch_3_ex_1_c.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_c.cpp -o bin/ch_3_ex_1_c
ch_3_ex_1_d: src/ch_3_ex_1_d.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_d.cpp -o bin/ch_3_ex_1_d
ch_3_ex_1_e: src/ch_3_ex_1_e.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1_e.cpp -o bin/ch_3_ex_1_e
ch_3_ex_1: src/ch_3_ex_1.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_1.cpp -o bin/ch_3_ex_1
ch_3_ex_2: src/ch_3_ex_2.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_2.cpp -o bin/ch_3_ex_2
ch_3_ex_3: src/ch_3_ex_3.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_3.cpp -o bin/ch_3_ex_3
ch_3_ex_4: src/ch_3_ex_4.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_4.cpp -o bin/ch_3_ex_4
ch_3_ex_5: src/ch_3_ex_5.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_5.cpp -o bin/ch_3_ex_5
ch_3_ex_6: src/ch_3_ex_6.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_6.cpp -o bin/ch_3_ex_6
ch_3_ex_7: src/ch_3_ex_7.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_7.cpp -o bin/ch_3_ex_7
ch_3_ex_8: src/ch_3_ex_8.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_8.cpp -o bin/ch_3_ex_8
ch_3_ex_9: src/ch_3_ex_9.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_9.cpp -o bin/ch_3_ex_9
ch_3_ex_10: src/ch_3_ex_10.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_10.cpp -o bin/ch_3_ex_10
ch_3_ex_11: src/ch_3_ex_11.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_3_ex_11.cpp -o bin/ch_3_ex_11
