ch_4_ex_1_a: src/ch_4_ex_1_a.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_1_a.cpp -o bin/ch_4_ex_1_a
ch_4_ex_1_b: src/ch_4_ex_1_b.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_1_b.cpp -o bin/ch_4_ex_1_b
ch_4_ex_1_c: src/ch_4_ex_1_c.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_1_c.cpp -o bin/ch_4_ex_1_c
ch_4_ex_1_d: src/ch_4_ex_1_d.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_1_d.cpp -o bin/ch_4_ex_1_d
ch_4_ex_1_e: src/ch_4_ex_1_e.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_1_e.cpp -o bin/ch_4_ex_1_e
ch_4_ex_2: src/ch_4_ex_2.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_2.cpp -o bin/ch_4_ex_2
ch_4_ex_3: src/ch_4_ex_3.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_3.cpp -o bin/ch_4_ex_3
ch_4_ex_4: src/ch_4_ex_4.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_4.cpp -o bin/ch_4_ex_4
ch_4_ex_5: src/ch_4_ex_5.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_5.cpp -o bin/ch_4_ex_5
ch_4_ex_6: src/ch_4_ex_6.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_6.cpp -o bin/ch_4_ex_6
ch_4_ex_7: src/ch_4_ex_7.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_7.cpp -o bin/ch_4_ex_7
ch_4_ex_8: src/ch_4_ex_8.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_8.cpp -o bin/ch_4_ex_8
ch_4_ex_9: src/ch_4_ex_9.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_9.cpp -o bin/ch_4_ex_9
ch_4_ex_10: src/ch_4_ex_10.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_10.cpp -o bin/ch_4_ex_10
ch_4_ex_11: src/ch_4_ex_11.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_11.cpp -o bin/ch_4_ex_11
ch_4_ex_12: src/ch_4_ex_12.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_12.cpp -o bin/ch_4_ex_12
ch_4_ex_13: src/ch_4_ex_13.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_13.cpp -o bin/ch_4_ex_13
ch_4_ex_14: src/ch_4_ex_14.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_14.cpp -o bin/ch_4_ex_14
ch_4_ex_15: src/ch_4_ex_15.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_15.cpp -o bin/ch_4_ex_15
ch_4_ex_16: src/ch_4_ex_16.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_16.cpp -o bin/ch_4_ex_16
ch_4_ex_17: src/ch_4_ex_17.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_17.cpp -o bin/ch_4_ex_17
ch_4_ex_18: src/ch_4_ex_18.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_18.cpp -o bin/ch_4_ex_18
ch_4_ex_19: src/ch_4_ex_19.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_19.cpp -o bin/ch_4_ex_19
ch_4_ex_20: src/ch_4_ex_20.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_20.cpp -o bin/ch_4_ex_20
ch_4_ex_21: src/ch_4_ex_21.cpp
	clang++ -Wall -std=c++14 -I../../../include src/ch_4_ex_21.cpp -o bin/ch_4_ex_21
